# netlify.toml

[build]
  command = "npm run install-playwright && npm install && npm run build"
  functions = ".netlify/functions"
  publish = "build"

[build.environment]
  MONGODB_URI = "mongodb+srv://Ravivarma:RavivarmaMongo@movie-phobics.x3v8z.mongodb.net/?retryWrites=true&w=majority&appName=movie-phobics"
  NODE_VERSION = "18"


