[build]
  functions = "src/handlers"  # Directory where your serverless functions are located

[[redirects]]
  from = "/api/*"
  to = "/api"
  status = 200

[[redirects]]
  from = "/404"
  to = "/custom-404.html"
  status = 404

[[redirects]]
  from = "/500"
  to = "/custom-500.html"
  status = 500
