# netlify.toml

[build]
  functions = ".netlify/functions"  # Directory where your serverless functions are located
  command = "npm install && npm run build"

[build.environment]
  MONGODB_URI = "mongodb+srv://Ravivarma:RavivarmaMongo@movie-phobics.x3v8z.mongodb.net/?retryWrites=true&w=majority&appName=movie-phobics"
  NODE_VERSION = "18"


