name: CI/CD

on:
  push:
    branches:
      - main
      - 'feature*'
  pull_request:
    branches:
      - main
      - 'feature*'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to be used'
        required: true
        default: 'v1.0.0'
  release:
    types: [published]

jobs:
  build_and_deploy-dev:
    runs-on: ubuntu-latest
    outputs:
      build-path: ./build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create build directory and build the project
        run: |
          mkdir -p build
          echo "This is a build artifact" > build/movie-phobics-backend.zip

      - name: List build directory
        run: ls -al ./build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

  create-release-version:
    needs: build_and_deploy-dev
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Get Latest Tag and Check for Changes
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          latest_commit=$(git rev-parse HEAD)

          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            last_tag_commit=$(git rev-list -n 1 "$latest_tag")
            if [ "$latest_commit" != "$last_tag_commit" ]; then
              version=$(echo "$latest_tag" | sed 's/v//')
              IFS='.' read -r major minor patch <<< "$version"
              new_patch=$((patch + 1))
              new_tag="v${major}.${minor}.${new_patch}"
            else
              echo "No new changes to tag."
              exit 0
            fi
          fi

          echo "New tag: $new_tag"
          echo "TAG_VERSION=$new_tag" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        if: env.TAG_VERSION != 'v1.0.0'
        id: create_tag
        run: |
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: env.TAG_VERSION != 'v1.0.0'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: ${{ env.TAG_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    needs: build_and_deploy-dev
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://moviephobics.netlify.app 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Install dependencies
        run: npm install

      - name: Deploying to Production
        run: echo "Deploying to Production..."

      - name: Deploy to Production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

      - name: Deployed to Production
        run: echo "Deployed to Production..."

  deploy-on-release:
    needs: build_and_deploy-dev
    if: github.event_name == 'release' && github.event.action == 'published' || (github.event_name == 'workflow_dispatch' && github.event.inputs.release_version)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Get Release Tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Deploying release tag ${{ github.event.inputs.release_version }}"
          else
            echo "Deploying release tag ${{ github.event.release.tag_name }}"
          fi

      - name: Deploy to Production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            npx netlify-cli deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --deploy-url ${{ github.event.inputs.release_version }}
          else
            npx netlify-cli deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
          fi

      - name: Deployed Release to Production
        run: echo "Deployed release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_version || github.event.release.tag_name }} to Production"
