name: CI/CD

on:
  push:
    branches:
      - main
      - 'feature*'
  pull_request:
    branches:
      - main
      - 'feature*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Building the project..."

      - name: Run tests
        run: echo "Running tests..."

      - name: Create build artifact
        run: |
          mkdir -p build
          echo "This is a build artifact" > build/movie-phobics-backend.zip
        # This step ensures the file exists; replace this with your actual build process

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."
        env:
          ENVIRONMENT: dev
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
        env:
          ENVIRONMENT: prod

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: |
          # Fetch all tags from the remote
          git fetch --tags
          # Get the latest tag (e.g., v1.0.0)
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          # Increment the version number
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            # Extract the current version number (e.g., 1.0.0)
            version=$(echo "$latest_tag" | sed 's/v//')
            # Split version into major, minor, patch
            IFS='.' read -r major minor patch <<< "$version"
            # Increment the patch number
            new_patch=$((patch + 1))
            new_tag="v${major}.${minor}.${new_patch}"
          fi
          echo "New tag: $new_tag"
          echo "TAG_VERSION=$new_tag" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        id: create_tag
        run: |
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: Release ${{ env.TAG_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List build directory before upload
        run: ls -al ./build
        # Ensure the file exists before uploading
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/movie-phobics-backend.zip
          asset_name: movie-phobics-backend.zip
          asset_content_type: application/zip
