name: CI/CD

on:
  push:
    branches:
      - main
      - 'feature*'
  pull_request:
    branches:
      - main
      - 'feature*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo "Building the project..."
      
      - name: Run tests
        run: echo "Running tests..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."
        env:
          ENVIRONMENT: dev
          
  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    environment: uat
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to UAT
        run: echo "Deploying to UAT environment..."
        env:
          ENVIRONMENT: uat

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Prod
        run: echo "Deploying to Production environment..."
        env:
          ENVIRONMENT: prod
