name: CI/CD

on:
  push:
    branches:
      - main
      - 'feature*'
  pull_request:
    branches:
      - main
      - 'feature*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo "Building the project..."
      
      - name: Run tests
        run: echo "Running tests..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: echo "Deploying to Dev environment..."
        env:
          ENVIRONMENT: dev
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
        env:
          ENVIRONMENT: prod

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Version Tag
        id: create_tag
        run: |
          # Bump version number using the latest commit hash or a strategy of your choice
          TAG_VERSION=$(date +'%Y%m%d%H%M%S') # Example: timestamp as version
          git tag v$TAG_VERSION
          git push origin v$TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.create_tag.outputs.version }}
          release_name: Release v${{ steps.create_tag.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/asset.zip
          asset_name: movie-phobics-backend.zip
          asset_content_type: application/zip
